-- MySQL Script generated by MySQL Workbench
-- Mon May 22 10:57:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema barberia_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema barberia_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `barberia_db` DEFAULT CHARACTER SET utf8 ;
USE `barberia_db` ;

-- -----------------------------------------------------
-- Table `barberia_db`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberia_db`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombreCliente` VARCHAR(45) NOT NULL,
  `apellidoCliente` VARCHAR(45) NOT NULL,
  `correoCliente` VARCHAR(45) NOT NULL,
  `passwordCliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barberia_db`.`FotoCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberia_db`.`FotoCliente` (
  `idFotoCliente` INT NOT NULL AUTO_INCREMENT,
  `contenidoFotoCliente` BLOB NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idFotoCliente`),
  INDEX `fk_FotoCliente_Cliente1_idx` (`Cliente_idCliente` ASC),
  UNIQUE INDEX `idFotoCliente_UNIQUE` (`idFotoCliente` ASC),
  CONSTRAINT `fk_FotoCliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `barberia_db`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barberia_db`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberia_db`.`Departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `nombreDepartamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartamento`),
  UNIQUE INDEX `idDepartamento_UNIQUE` (`idDepartamento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barberia_db`.`Distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberia_db`.`Distrito` (
  `idDistrito` INT NOT NULL AUTO_INCREMENT,
  `nombreDistrito` VARCHAR(45) NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idDistrito`),
  INDEX `fk_Distrito_Departamento1_idx` (`Departamento_idDepartamento` ASC),
  UNIQUE INDEX `idDistrito_UNIQUE` (`idDistrito` ASC),
  CONSTRAINT `fk_Distrito_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `barberia_db`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barberia_db`.`Barberia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberia_db`.`Barberia` (
  `idBarberia` INT NOT NULL AUTO_INCREMENT,
  `nombreBarberia` VARCHAR(45) NOT NULL,
  `direccionBarberia` VARCHAR(45) NOT NULL,
  `Distrito_idDistrito` INT NOT NULL,
  PRIMARY KEY (`idBarberia`),
  INDEX `fk_Barberia_Distrito1_idx` (`Distrito_idDistrito` ASC),
  UNIQUE INDEX `idBarberia_UNIQUE` (`idBarberia` ASC),
  CONSTRAINT `fk_Barberia_Distrito1`
    FOREIGN KEY (`Distrito_idDistrito`)
    REFERENCES `barberia_db`.`Distrito` (`idDistrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barberia_db`.`Barbero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberia_db`.`Barbero` (
  `idBarbero` INT NOT NULL AUTO_INCREMENT,
  `nombreBarbero` VARCHAR(45) NOT NULL,
  `apellidoBarbero` VARCHAR(45) NOT NULL,
  `apodoBarbero` VARCHAR(45) NOT NULL,
  `correoBarbero` VARCHAR(45) NOT NULL,
  `passwordBarbero` VARCHAR(45) NOT NULL,
  `descripcionBarbero` VARCHAR(45) NOT NULL,
  `telefonoBarbero` VARCHAR(11) NOT NULL,
  `contenidoFotoPerfilBarbero` BLOB NOT NULL,
  `Barberia_idBarberia` INT NOT NULL,
  PRIMARY KEY (`idBarbero`),
  INDEX `fk_Barbero_Barberia1_idx` (`Barberia_idBarberia` ASC),
  UNIQUE INDEX `idBarbero_UNIQUE` (`idBarbero` ASC),
  CONSTRAINT `fk_Barbero_Barberia1`
    FOREIGN KEY (`Barberia_idBarberia`)
    REFERENCES `barberia_db`.`Barberia` (`idBarberia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barberia_db`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberia_db`.`Servicio` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `nombreServicio` VARCHAR(45) NOT NULL,
  `descripcionServicio` VARCHAR(45) NOT NULL,
  `precioServicio` DECIMAL NOT NULL,
  `estadoServicio` VARCHAR(45) NOT NULL,
  `Barbero_idBarbero` INT NOT NULL,
  PRIMARY KEY (`idServicio`),
  INDEX `fk_Servicio_Barbero1_idx` (`Barbero_idBarbero` ASC),
  UNIQUE INDEX `idServicio_UNIQUE` (`idServicio` ASC),
  CONSTRAINT `fk_Servicio_Barbero1`
    FOREIGN KEY (`Barbero_idBarbero`)
    REFERENCES `barberia_db`.`Barbero` (`idBarbero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barberia_db`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberia_db`.`Reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `fechaReserva` VARCHAR(45) NOT NULL,
  `estadoReserva` VARCHAR(45) NOT NULL,
  `Barbero_idBarbero` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Servicio_idServicio` INT NOT NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_Reserva_Barbero1_idx` (`Barbero_idBarbero` ASC),
  INDEX `fk_Reserva_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Reserva_Servicio1_idx` (`Servicio_idServicio` ASC),
  UNIQUE INDEX `idReserva_UNIQUE` (`idReserva` ASC),
  CONSTRAINT `fk_Reserva_Barbero1`
    FOREIGN KEY (`Barbero_idBarbero`)
    REFERENCES `barberia_db`.`Barbero` (`idBarbero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `barberia_db`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `barberia_db`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barberia_db`.`ColaDeReservaEnServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberia_db`.`ColaDeReservaEnServicio` (
  `Servicio_idServicio` INT NOT NULL,
  `Reserva_idReserva` INT NOT NULL,
  INDEX `fk_ColaDeReservaEnServicio_Servicio_idx` (`Servicio_idServicio` ASC),
  INDEX `fk_ColaDeReservaEnServicio_Reserva1_idx` (`Reserva_idReserva` ASC),
  CONSTRAINT `fk_ColaDeReservaEnServicio_Servicio`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `barberia_db`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ColaDeReservaEnServicio_Reserva1`
    FOREIGN KEY (`Reserva_idReserva`)
    REFERENCES `barberia_db`.`Reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barberia_db`.`Opinion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberia_db`.`Opinion` (
  `idOpinion` INT NOT NULL AUTO_INCREMENT,
  `nombreOpinion` VARCHAR(45) NOT NULL,
  `descripcionOpinion` VARCHAR(45) NOT NULL,
  `notaOpinion` VARCHAR(45) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Barbero_idBarbero` INT NOT NULL,
  PRIMARY KEY (`idOpinion`),
  INDEX `fk_Opinion_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Opinion_Barbero1_idx` (`Barbero_idBarbero` ASC),
  UNIQUE INDEX `idOpinion_UNIQUE` (`idOpinion` ASC),
  CONSTRAINT `fk_Opinion_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `barberia_db`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Opinion_Barbero1`
    FOREIGN KEY (`Barbero_idBarbero`)
    REFERENCES `barberia_db`.`Barbero` (`idBarbero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barberia_db`.`FotoPortafolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberia_db`.`FotoPortafolio` (
  `idFotoPortafolio` INT NOT NULL AUTO_INCREMENT,
  `contenidoFotoPortafolio` BLOB NOT NULL,
  `Barbero_idBarbero` INT NOT NULL,
  PRIMARY KEY (`idFotoPortafolio`),
  INDEX `fk_FotoPortafolio_Barbero1_idx` (`Barbero_idBarbero` ASC),
  UNIQUE INDEX `idFotoPortafolio_UNIQUE` (`idFotoPortafolio` ASC),
  CONSTRAINT `fk_FotoPortafolio_Barbero1`
    FOREIGN KEY (`Barbero_idBarbero`)
    REFERENCES `barberia_db`.`Barbero` (`idBarbero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barberia_db`.`Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberia_db`.`Especialidad` (
  `idEspecialidad` INT NOT NULL AUTO_INCREMENT,
  `nombreEspecialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEspecialidad`),
  UNIQUE INDEX `idEspecialidad_UNIQUE` (`idEspecialidad` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barberia_db`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberia_db`.`Tag` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `nombreTag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTag`),
  UNIQUE INDEX `idTag_UNIQUE` (`idTag` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barberia_db`.`TagBarbero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberia_db`.`TagBarbero` (
  `Tag_idTag` INT NOT NULL,
  `Barbero_idBarbero` INT NOT NULL,
  INDEX `fk_TagBarbero_Tag1_idx` (`Tag_idTag` ASC),
  INDEX `fk_TagBarbero_Barbero1_idx` (`Barbero_idBarbero` ASC),
  CONSTRAINT `fk_TagBarbero_Tag1`
    FOREIGN KEY (`Tag_idTag`)
    REFERENCES `barberia_db`.`Tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TagBarbero_Barbero1`
    FOREIGN KEY (`Barbero_idBarbero`)
    REFERENCES `barberia_db`.`Barbero` (`idBarbero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barberia_db`.`BarberoEspecialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberia_db`.`BarberoEspecialidad` (
  `Especialidad_idEspecialidad` INT NOT NULL,
  `Barbero_idBarbero` INT NOT NULL,
  INDEX `fk_BarberoEspecialidad_Barbero1_idx` (`Barbero_idBarbero` ASC),
  INDEX `fk_BarberoEspecialidad_Especialidad1_idx` (`Especialidad_idEspecialidad` ASC),
  CONSTRAINT `fk_BarberoEspecialidad_Barbero1`
    FOREIGN KEY (`Barbero_idBarbero`)
    REFERENCES `barberia_db`.`Barbero` (`idBarbero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BarberoEspecialidad_Especialidad1`
    FOREIGN KEY (`Especialidad_idEspecialidad`)
    REFERENCES `barberia_db`.`Especialidad` (`idEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
